### ISSUE TITLE
Add an env variable for the starting balance

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#62]
ℹ️ This issue is part of Epic #55

## Objective

Add a new application environment for the following environments:
- Development: `dev.example`.
- Testing: `test.exs`
- Production: `runtime.exs`

This variable should be used by the `Accounts` context for account creation, specifically in the crypto modules (`stellar.ex`)

## Checklist

* [ ] The application environment variable should be named `starting_balance` and the root key belongs to `mintacoin`.
* [ ] The value is set by a system environment variable called **"STARTING_BALANCE"**.
* [ ] The default value for this variable is `10`.

**Comment by Odraxs** [comment]
Hi, I would like to be assigned to this issue

And a question the variable "STARTING_BALANCE" is called by `get_env` in the target files or in Accounts create function ?

**Comment by SanGeeky** [comment]
@Odraxs I will assign this issue to you. Related to your question is required also in the implementation of the Stellar crypto functions for accounts.

Remember when you get the variable, the value is instanced as String, so you will need to cast the value, and this value can be float.

**Comment by Odraxs** [comment]
@SanGeeky Hello

I started working and I have some questions
1. To be sure the "STARTING_BALANCE" is set directly in the `dev.exs` file or the value is set there via `System.get_env` ?
2. This value is needed in stellar.ex to set the starting_balance in `build_create_account_operation` (i already change it), then this is creating the wallet and the balance to be store into the db ? In the case is not i guess that is what this mean ?
 > This variable should be used by the Accounts context for the account creation.

Then i guess in the `create_account.ex` file needs to implement the creation of the balance because i find the wallet is created there ? 
Or I'm going further than this issue is ?

**Comment by SanGeeky** [comment]
@Odraxs I hope this helps:

1. Well, the value should be set in `dev.example` via `System.get_env` and do not forget to use a default value of 10.
2. Is only required in the crypto module `stellar.ex` which belongs to the Accounts context. 


Regarding the other question, the balance of wallets is defined by the asset supply, set when we create an asset; In this issues, we are referring to the define the starting balance to create a Stellar account, [check out this documentation](https://developers.stellar.org/docs/fundamentals-and-concepts/lumens#minimum-balance).
